In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Use a Tuple to create np array

In [4]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Different Dimentions of Array

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a, a.ndim)
print(b, b.ndim)
print(c, c.ndim)
print(d, d.ndim)

42 0
[1 2 3 4] 1
[[1 2 3]
 [4 5 6]] 2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 3


In [8]:
arr = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr, arr.ndim)

[[[[[1 2 3 4 5]]]]] 5


Accessing elements in numpy array

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a[0])
b = np.array([[2, 3, 4], [6, 7, 8]])
print(b[1, 2])
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[4, 7], [3, 9]]])
print(c[1, 0, 1])

1
8
6


Slicing Array

In [11]:
print(a[2: 5])
print(b[1,:2])

[3 4 5]
[6 7]


Terms of COPY and VIEW

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
x = arr.copy()
print(arr, x)
arr[0] = 10
print(arr, x)
x[0] = 5
print(arr,x)

[1 2 3 4 5 6 7] [1 2 3 4 5 6 7]
[10  2  3  4  5  6  7] [1 2 3 4 5 6 7]
[10  2  3  4  5  6  7] [5 2 3 4 5 6 7]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
x = arr.view()
print(arr, x)
arr[0] = 10
print(arr, x)
x[0] = 5
print(arr,x)

[1 2 3 4 5 6 7] [1 2 3 4 5 6 7]
[10  2  3  4  5  6  7] [10  2  3  4  5  6  7]
[5 2 3 4 5 6 7] [5 2 3 4 5 6 7]


Shape and Reshape

In [18]:
arr = np.array([[1, 2, 3, 4, 5, 6],[6, 7, 8, 9, 10, 11]])
print(arr.shape)

(2, 6)


In [19]:
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]


Different Ways of Iteration

In [20]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [24]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


Different Ways of JOINING Array

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Splitting Numpy Array

In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


Search in Numpy Array

In [34]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [35]:
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 6]),)


In [36]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [37]:
x = np.searchsorted(arr, 7, side='right')
print(x)

2


SORTING in Numpy Array

In [38]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [39]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [40]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [41]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
